ALTER TABLE RegisterCrime DROP CONSTRAINT FKRegisterCr539537;
ALTER TABLE RegisterCrime DROP CONSTRAINT FKRegisterCr993854;
ALTER TABLE Census DROP CONSTRAINT FKCensus735415;
DROP TABLE IF EXISTS Census CASCADE;
DROP TABLE IF EXISTS City CASCADE;
DROP TABLE IF EXISTS CrimesType CASCADE;
DROP TABLE IF EXISTS RegisterCrime CASCADE;

